# Composite action to publish MPI Operator images.
name: Build And Publish Container Images
description: Build Multiplatform Supporting Container Images

inputs:
  image:
    required: true
    description: image tag
  dockerfile:
    required: true
    default: Dockerfile
    description: path for Dockerfile
  platforms:
    required: true
    description: e.g, linux/amd64
  suffix:
    required: false
    description: e.g, -openmpi
  context:
    required: false
    default: .
    description: e.g, build/base
  output-artifact-name:
    required: true
    description: e.g, mpi-operator
  load-artifact-name:
    required: false
    description: e.g, openmpi-builder
runs:
  using: composite
  steps:
    - name: Set up Docker
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      uses: crazy-max/ghaction-setup-docker@v1
      with:
        version: v24.0.5
#      shell: bash
#      run: |
#        docker version
#        for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do sudo apt-get remove $pkg; done

    - name: Set Up contained image store
      shell: bash
      run: |
        cat /etc/docker/daemon.json | jq '. | .+{"features": {"containerd-snapshotter": true}, "experimental": true}' | sudo tee /etc/docker/daemon.json
        cat ~/.docker/config.json | jq '. | .+{"experimental": "enabled"}' | sudo tee ~/.docker/config.json
        sudo systemctl restart docker

        docker info -f '{{ .DriverStatus }}'
        docker info

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ inputs.platforms }}

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v2

#    - name: debug
#      shell: bash
#      run: |
#        docker info -f '{{ .DriverStatus }}'
#        cat /etc/docker/daemon.json | \
#          jq '. | .+{"features": {"containerd-snapshotter": true}, "storage-driver": "stargz", "experimental": true}' | sudo tee /etc/docker/daemon.json
#        sudo mkdir -p /etc/containerd
#        sudo tee /etc/containerd/config.toml <<EOF
#        version = 2
#
#        [proxy_plugins]
#        [proxy_plugins.stargz]
#        type = "snapshot"
#        address = "/run/containerd-stargz-grpc/containerd-stargz-grpc.sock"
#        EOF
#
#        sudo apt-get install fuse
#        modprobe fuse
#        wget -qO stargz-snapshotter-v0.14.3-linux-amd64.tar.gz https://github.com/containerd/stargz-snapshotter/releases/download/v0.14.3/stargz-snapshotter-v0.14.3-linux-amd64.tar.gz
#        tar -C /usr/local/bin -xvf stargz-snapshotter-v0.14.3-linux-amd64.tar.gz containerd-stargz-grpc ctr-remote
#        sudo wget -O /etc/systemd/system/stargz-snapshotter.service https://raw.githubusercontent.com/containerd/stargz-snapshotter/main/script/config/etc/systemd/system/stargz-snapshotter.service
#
#        sudo systemctl enable --now stargz-snapshotter || (journalctl -xeu docker.service && docker info && exit 1)
#        sudo systemctl restart containerd || (journalctl -xeu docker.service && docker info && exit 1)
#        sudo systemctl restart docker || (journalctl -xeu docker.service && docker info && exit 1)
#
#        docker info -f '{{ .DriverStatus }}'
#        docker info

    - name: Docker meta
      if : ${{ inputs.suffix == '' }}
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Docker meta with suffix
      if : ${{ inputs.suffix != '' }}
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          suffix=${{ inputs.suffix }},onlatest=true

    - name: Download artifact
      if: ${{ inputs.load-artifact-name != '' }}
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.load-artifact-name }}
        path: /tmp

    - name: Load Image
      if: ${{ inputs.load-artifact-name != '' }}
      shell: bash
      run: |
        docker load --input /tmp/${{ inputs.load-artifact-name }}.tar
        docker image ls -a

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        platforms: ${{ inputs.platforms }}
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
#        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.DOCKER_METADATA_OUTPUT_TAGS }}
        labels: ${{ steps.meta.outputs.labels }}
        outputs: type=oci,dest=/tmp/${{ inputs.output-artifact-name }}.tar
        build-args:
          port=2222

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
          name: ${{ inputs.output-artifact-name }}
          path: /tmp/${{ inputs.output-artifact-name }}.tar
